package:
  name: bcrypt
  version: "1.0.2"

source:
  fn: bcrypt-1.0.2.tar.gz
  url: https://pypi.python.org/packages/source/b/bcrypt/bcrypt-1.0.2.tar.gz
  md5: c5df008669d17dd6eeb5e2042d5e136f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bcrypt = bcrypt:main
    #
    # Would create an entry point called bcrypt that calls bcrypt.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - cffi

  run:
    - python
    - cffi

test:
  # Python imports
  imports:
    - bcrypt

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/dstufft/bcrypt/
  license: Apache License, Version 2.0
  summary: u'Modern password hashing for your software and your servers'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
